chat/urls.py
from django.urls import path
from . import views,api

app_name = "chat"

urlpatterns = [
    #templates
    path('',views.chat,name="home"),
    path('dashboard',views.dashboard,name="dashboard"),
    
    #APIs
    path('v1/get-response',api.getResponse,name="get-response")
]

quik/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('chat.urls')),
    path('',include('user_auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user_auth/urls.py
from django.urls import path
from . import views

app_name = "user_auth"

urlpatterns = [
    path('register',views.register,name="register"),
    path('login',views.user_login,name="login"),
    path('logout',views.logout_url,name="logout"),
]

chat/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
import os
from dotenv import load_dotenv

# Create your models here.
class Chats(models.Model):
    
    question = models.TextField(null=True,blank=True)
    answer = models.TextField(null=True,blank=True)
    created_at = models.DateTimeField(default=datetime.now())
    
    class Meta:
        db_table = "chats"
        
class Attachments(models.Model):
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    uploaded_at = models.DateTimeField(default=datetime.now())
    attachment = models.FileField(upload_to='uploads/attachments/',null=True)
    
    class Meta:
        db_table = "attachments"

chat/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .models import Attachments

# Create your views here.
def chat(request,template='chat/home.html'):
    if request.user.is_authenticated:
        return redirect('chat:dashboard')
    else:
        return render(request,template)

@login_required
def dashboard(request,template='chat/dashboard.html'):
    uploads = Attachments.objects.filter(user_id=request.user.id).order_by('-uploaded_at')
    if request.method == "POST" and request.FILES['attachment']:
        file = request.FILES['attachment']
        Attachments.objects.create(attachment=file,user=request.user)
    return render(request,template,{'uploads':uploads})

user_auth/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.views.decorators.csrf import csrf_protect,csrf_exempt
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from .serializers import RegisterSerializer
from django.contrib.auth.hashers import make_password

# Create your views here.
@csrf_protect
def register(request,template_name="auth/register.html"):
    if request.method == "POST":
        postdata = request.POST
        serializer = RegisterSerializer(data=postdata)
        if serializer.is_valid():
            try:
                user = User.objects.filter(Q(username=postdata['username']) | Q(email=postdata['email'])).count()
            except:
                user = None
            if not user:
                user = User.objects.create(username=postdata['username'],password=make_password(postdata['password']),email=postdata['email'],first_name=postdata['name'])
                login(request,user)
                messages.success(request, "Registered Successfully" )
                return redirect('chat:dashboard')
            else:
                messages.error(request, "Email already Exists.")
        else:
            field_names = []
            for field_name, field_errors in serializer.errors.items():
                print(field_name, field_errors)
            field_names.append(field_name)
            message = f'Invalid data in {field_names}'
            messages.error(request, message )
    return render(request,template_name)

@csrf_protect
def user_login(request,template_name="auth/login.html"):
    if request.method == "POST":
        try:
            postdata = request.POST
            username = postdata['username']
            password = postdata['password']
            try:
                user = authenticate(username=username, password=password)
            except:
                user = None
            if user is not None:
                login(request,user)
                messages.success(request, "Logged In" )
                return redirect('chat:dashboard')
            else:
                messages.error(request, "User not found")
        except Exception as e:
            messages.error(request, "Some Error Occured")
    return render(request,template_name)


def logout_url(request):
    logout(request)
    messages.success(request, "Logged Out" )
    return redirect('chat:home')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <link
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      rel="stylesheet"
    />
    <link
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
      rel="stylesheet"
    />
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"
    ></script>
    <script
      type="text/javascript"
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js"
    ></script>
    <link href="{% static 'css/base.css'%}" rel="stylesheet" />
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
      <div class="container">
        <a class="navbar-brand" href="#"> Quik </a>
        {% if user.is_authenticated %}
        <span style="color: white">
          Hello, {{ user.first_name }}
          &nbsp<button type="button" class="btn btn-light"><a class="text-dark" href="{% url 'user_auth:logout' %}"> Logout </a></button>
        </span>
        {% else%}
        <button type="button" class="btn btn-light">
          <a class="text-dark" href="{% url 'user_auth:login' %}"> Login </a>
        </button>
        {% endif %}
      </div>
    </nav>
    {% include 'messages.html' %} {% block content %} {% endblock content %}
  </body>

  <script>
    $(document).ready(function () {
      // messages timeout for 10 sec
      setTimeout(function () {
        $(".messages").fadeOut("slow");
      }, 1000); // <-- time in milliseconds, 1000 =  1 sec
    });
  </script>
</html>

templates/chat/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link href="{% static 'css/chat.css'%}" rel="stylesheet" />
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row d-flex justify-content-center m-auto">

            <div class="col-md-3">
                <div class="card-header text-light bg-dark">
                    <h4 class="card-title"><strong>Uploaded Files</strong></h4>
                </div>

                <div class="border border-dark ps-container ps-theme-default ps-active-y" id="uploads" style="overflow-y: scroll !important; height:400px !important; ">
                    <div class="card p-2 border">
                        {% for f in uploads%}
                        <div class="p-1 card-body border border-dark">
                            <h6 class="card-title p-0">{{f.attachment.name}}</h6>
                            <p class="card-text small ">{{f.uploaded_at}}</p>
                          {% comment %} <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> {% endcomment %}
                          {% comment %} <a href="#" class="btn btn-primary">Button</a> {% endcomment %}
                        </div>
                        {%endfor%}
                      </div>
                      
                    </div>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input id="file-input" name="attachment" type="file"/>
                        <button type="submit">Upload</button>
                    </form>
                </div>
            <div class="col-md-9">
                <div class="card card-bordered rounded-top border border-dark">

                    <div class="card-header bg-dark">
                        <h4 class="card-title text-light"><strong>Chat</strong></h4>
                    </div>


                    <div class="ps-container ps-theme-default ps-active-y" id="chat-content" style="overflow-y: scroll !important; height:400px !important; ">
                        <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 0px;">
                            <div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;">

                            </div>.
                        </div>
                        <div class="ps-scrollbar-y-rail" style="top: 0px; height: 0px; right: 2px;">
                            <div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 2px;">

                            </div>
                        </div>
                    </div>


                    <div class="publisher bt-1 border-light">
                        <img class="avatar avatar-xs" src="https://img.icons8.com/color/36/000000/administrator-male.png" alt="...">
                        <input class="publisher-input" type="text" placeholder="Write something" name="question" id="question">
                        <span class="publisher-btn file-group">
                            
                            
                            {% comment %} {% if user.is_authenticated %}
                                <label for="file-input">
                                    <i class="fa fa-paperclip file-browser"></i>
                                </label>
                                <input id="file-input" type="file"/>
                            {% else %}
                                <a href="{% url 'user_auth:login'%}"><i class="fa fa-paperclip file-browser" ></i></a>
                            {% endif %} {% endcomment %}
                        
                        </span>
                        <a class="publisher-btn" href="#" data-abc="true"><i class="fa fa-smile"></i></a>
                        <a class="publisher-btn text-info" onclick="getResponse()" data-abc="true"><i class="fa fa-paper-plane"></i></a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        $("#file-input").change(function(){
            console.log(this.value)
        });
    });
</script>
<script type="text/javascript" src="{% static 'js/chat.js'%} "></script>
{% endblock content %}

templates/chat/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link href="{% static 'css/chat.css'%}" rel="stylesheet" />
<div class="page-content page-container" id="page-content">
    <div class="padding">

        <div class="jumbotron jumbotron-fluid">
            <div class="container">
              <h1 class="display-4">Hey <i class="fa fa-fa-hand-lizard"></i><img class="img-circle" style="height:80px" src="https://img.icons8.com/emoji/512/waving-hand-emoji.png"></h1>
              <p class="lead">Login to upload files and get data-driven response!</p>
            </div>
        </div>

        
          <div class="row container d-flex justify-content-center m-auto">
            <div class="col-md-9">
                <div class="card card-bordered rounded-top  border-dark">

                    <div class="card-header bg-dark">
                        <h4 class="card-title text-light"><strong>Chat</strong></h4>
                        <a class="btn btn-xs btn-secondary" href="#" data-abc="true">Let's Chat App</a>
                    </div>


                    <div class="ps-container ps-theme-default ps-active-y" id="chat-content" style="overflow-y: scroll !important; height:400px !important; ">
                        <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 0px;">
                            <div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;">

                            </div>.
                        </div>
                        <div class="ps-scrollbar-y-rail" style="top: 0px; height: 0px; right: 2px;">
                            <div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 2px;">

                            </div>
                        </div>
                    </div>


                    <div class="publisher bt-1 border-light">
                        <img class="avatar avatar-xs" src="https://img.icons8.com/color/36/000000/administrator-male.png" alt="...">
                        <input class="publisher-input" type="text" placeholder="Give it a try, ask something." name="question" id="question">
                        <span class="publisher-btn file-group">
                            
                            
                            {% if user.is_authenticated %}
                                <label for="file-input">
                                    <i class="fa fa-paperclip file-browser"></i>
                                </label>
                                <input id="file-input" type="file"/>
                            {% else %}
                                <a href="{% url 'user_auth:login'%}"><i class="fa fa-paperclip file-browser" ></i></a>
                            {% endif %}
                        
                        </span>
                        <a class="publisher-btn" href="#" data-abc="true"><i class="fa fa-smile"></i></a>
                        <a class="publisher-btn text-info" onclick="getResponse()" data-abc="true"><i class="fa fa-paper-plane"></i></a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="{% static 'js/chat.js'%} "></script>
{% endblock content %}

templates/messages.html
{% if messages %}
<ul class="mask messages w-25" style="margin: auto !important">
    {% for message in messages %}
    <div class="alert {{ message.tags }} " role="alert">
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </div>
</ul>
{% endif %}